### ISSUE TITLE
Error 401 Solution

### ISSUE THREAD

**Issue by AdityaSeth777** [arkapg211002/AskAI#2]
![image](https://user-images.githubusercontent.com/108742527/212893370-99385980-f17d-4a91-ac5b-75e9ecdc2112.png)

I want to solve the error in this repository. Should I open a PR and do it ?
Maybe now or after our sem exams.

Aditya.

**Comment by arkapg211002** [comment]
Ok

**Comment by arkapg211002** [comment]
@AdityaSeth777 issue resolved. I have noted the steps that worked for me in the readme of this repo. Thanks though for raising the issue. I am closing it as of now.

**Comment by AdityaSeth777** [comment]
Okay. Great !
